[package]
name = "BorromaRust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
fixed_index_vec = { git = "https://github.com/JorgeRicoVivas/fixed_index_vec" }